TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MyFIRSTJavaOpMode_Oliver.java
=> oyip-20190911

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PushbotAutoDriveByEncoder_Linear.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PushbotAutoDriveByGyro_Linear.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PushbotAutoDriveByTime_Linear.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PushbotAutoDriveToLine_Linear.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TensorFlowSkystoneDetection.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/VuforiaSkyStoneNavigation.java
Adding sample programs to Team folder for testing:
- Vuforia
- Tensorflow
- Autonomous mode - Encoder, Gyro
=> Adding sample programs to Team folder for testing

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Ronok.java
Code that changes with majority
=> This is the good boi code.

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Almondjoyismelindasson.java
melinda is apotatowhich is her aunt
=> i changed the double to be mielindas daughter

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ALmondJoy420.java
Yo, Big Shaq, the one and only
Man's not hot, never hot
Skrrat, skidi-kat-kat
Boom
Two plus two is four, minus one that's three, quick maths
Everyday man's on the block, smoke trees
See your girl in the park, that girl is a uckers
When the ting went quack-quack-quack, you man were ducking (you man ducked)
Hold tight, Asnee (my brotha), he's got the pumpy (big ting)
Hold tight, my man (my guy), he's got the frisbee
I trap, trap, trap on the phone, movin' that cornflakes
Rice Krispies, hold tight my girl, Whitney (my G)
On the road doin' ten toes, like my toes (like my toes)
You man thought I froze, I see a peng girl, then I pose (chilin')
If she ain't on it, I ghost, hah, look at your nose (check your nose fam)
You donut, nose long like garden hose
I tell her man's not hot, I tell her …
=> I plead the fifth

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Mecanum_Drive.java
Added gyro assistance in drive and support for touch sensors in arm
=> Added gyro assistance in drive and support for touch sensors in arm

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Mecanum_Drive.java
Auto drive with color sensor
TeleOps mode with additional servos for front grab, side grab and claw rotation
=> Color sensor, servos for front and side grabbers, claw rotation

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SensorMRColor2.java
write output of color sensor 2 at telemetry
=> distancesensor_colorsensor2

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SensorTouch.java
=> add touch sensor control code

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SensorDistance.java, build.gradle
update, test and get distance sensor programming working
=> SensorDistance

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SkyStone_Detect.java
Detect Skystone using color sensor
=> Skystone_Detect_ColorSensor

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum.java
=> BaseBotMove Improvement

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum_ParkLeft.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum_ParkRight.java
Consolidate code from park left and park right and also orginal automonous drive
=> Consolidate code from park left and park right and also orginal automonous drive

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum.java
add back orginal automonous drive before forking into left park and rgiht park code
=> add back orginal automonous drive before forking into left park and rgiht park code

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum.java
Fine tune DM_Auto_Mecanum to park alway
=> Fine tune DM_Auto_Mecanum to park alway 

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum_ParkLeftPrototype.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_DriveTestIMU.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Playgrounds/Forward_Alan.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Prototypes/ConceptTensorFlowObjectDetectionWebcam.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Prototypes/Mecanum_Base_Drive.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Prototypes/PushbotAutoDriveByEncoder.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Prototypes/PushbotAutoDriveByGyro.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Prototypes/SensorBNO055IMU.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Prototypes/SensorMRColor2.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Prototypes/SkyStone_Detect.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SensorDistance.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SensorMRColor_Test.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SensorTouch.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/testPushbotPOV.java
=> Enable only competition codes 

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Mecanum_Drive.java
Move the robot to the right position to pick up stone first after press Start Button
=> Move to the pick up stone position first after press Start Button

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Mecanum_Drive.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Playgrounds/Turning_Alan.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Prototypes/DM_Auto_Simple.java
add backside servo control to pitch capstone or move skystone
=> add backside servo control to pitch capstone or move skystone

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum_ParkLeft.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum_ParkLeftPrototype.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/HolonomicDrive.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Mecanum_Drive.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Playgrounds/PushbotAutoDriveByEncoder_Linear.java
moveFwdAndBackForMilliseconds and moveSidewayForMilliseconds
=> add base bot move fwd/backward and sideway by time duration

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum_Base.java
Add some helper functions, rotate and move by distance
=> Add some helper functions, rotate and move by distance

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Mecanum_Drive.java
Add safety code during intialization so that robot can be stopped.
=> Add safety code during intialization so that robot can be stopped. 

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum_Base.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum_Left.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum_Right.java
Fine Tune Porgram of ParkLeft and ParkRIght to be gental
=> Fine Tune Porgram of ParkLeft and ParkRIght to be gental 

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Mecanum_Drive.java
=> Revision after Dec 4 evening

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Mecanum_Drive.java
Version right before Dec 7 meet
=> Revision after Dec 6 evening

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Skystone_Base.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Skystone_Right.java
Autonomous program for Skystone
=> Autonomous program for Skystone

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Skystone_Left.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Skystone_Right.java
Revise autonomous program to recognize Skystone and park on the left
=> Revise autonomous program to recognize Skystone and park on the left

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Skystone_Base.java
Move bot further to the right before putting down grabber (when parking to left)
=> Move bot further to the right before putting down grabber (when parking to left)

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Skystone_Left.java
Lift left grabber to lesser extent
=> Lift left grabber to lesser extent

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum_Left.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum_Park_LeftBack.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum_Park_LeftFront.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum_Park_RightBack.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum_Park_RightFront.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum_Right.java
Move bot closer to foundation during Foundation autonomous
=> Move bot closer to foundation during Foundation autonomous

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum_Park_LeftFront.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum_Park_RightFront.java
Tuning for parking (front) programs
=> Tuning for parking (front) programs

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum_Left.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Mecanum_Right.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Skystone_Base.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Skystone_Left.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Skystone_Right.java
=> Updates on Jan 19

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Mecanum_Drive.java
Updates on Jan 21 to fix grabber servo
=> Updates on Jan 21 to fix grabber servo

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Skystone_Base.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DM_Auto_Skystone_Left.java
Updates on Jan 26 to update Autonomous program Skystone parking on left
=> Updates on Jan 26 to update Autonomous program Skystone parking on left
